version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/stocks
    ports:
      - "8001:80"
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "python", "main.py"]

volumes:
  postgres_data:
